# Generated by Django 4.0.3 on 2022-03-30 20:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Goals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_goal', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=1)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Payments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mollie_id', models.CharField(max_length=255)),
                ('amount_eur', models.CharField(max_length=255)),
                ('checkout_url', models.URLField()),
                ('status', models.CharField(max_length=1)),
                ('datetime', models.DateTimeField()),
            ],
        ),
    ]
