# Generated by Django 4.0.3 on 2022-04-02 08:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('github_username', models.CharField(max_length=255)),
                ('repo', models.CharField(max_length=255)),
                ('commit_goal', models.PositiveIntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(choices=[('i', 'in progress'), ('s', 'succesfull'), ('f', 'failed')], default='i', max_length=1)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField()),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('mollie_id', models.CharField(max_length=255)),
                ('amount_eur', models.CharField(max_length=255)),
                ('checkout_url', models.URLField()),
                ('payment_status', models.CharField(choices=[('o', 'open'), ('c', 'canceled'), ('u', 'pending'), ('a', 'authorized'), ('e', 'expired'), ('f', 'failed'), ('p', 'paid')], default='o', max_length=1)),
                ('datetime', models.DateTimeField()),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='motivator.goal')),
            ],
        ),
    ]
