# Generated by Django 4.0.3 on 2022-04-25 11:51

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motivator', '0002_alter_goal_amount_alter_goal_commit_goal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 4, 25, 11, 51, 9, 362877, tzinfo=utc))]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(datetime.datetime(2022, 4, 25, 11, 51, 9, 362451, tzinfo=utc))]),
        ),
    ]
