# Generated by Django 4.0.3 on 2022-04-25 11:51

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('motivator', '0003_alter_goal_end_date_alter_goal_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)]),
        ),
    ]
