# Generated by Django 4.0.3 on 2022-06-27 08:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import motivator.validators


class Migration(migrations.Migration):

    dependencies = [
        ('motivator', '0004_alter_goal_end_date_alter_goal_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goal',
            name='end_date',
            field=models.DateTimeField(validators=[motivator.validators.date_validator_min]),
        ),
        migrations.AlterField(
            model_name='goal',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, validators=[motivator.validators.date_validator_min]),
        ),
        migrations.AlterField(
            model_name='payment',
            name='datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='payment',
            name='goal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='motivator.goal'),
        ),
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('refund_id', models.CharField(max_length=255)),
                ('amount_eur', models.CharField(max_length=255)),
                ('refund_status', models.CharField(choices=[('o', 'open'), ('c', 'canceled'), ('u', 'pending'), ('a', 'authorized'), ('e', 'expired'), ('f', 'failed'), ('p', 'paid')], default='o', max_length=1)),
                ('datetime', models.DateTimeField(default=django.utils.timezone.now)),
                ('goal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='refund', to='motivator.goal')),
                ('payment', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='motivator.payment')),
            ],
        ),
    ]
