# Generated by Django 4.0.3 on 2022-06-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivator', '0005_alter_goal_end_date_alter_goal_start_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='mollie_id',
            new_name='payment_id',
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount_eur',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount_eur',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
