# Generated by Django 4.0.3 on 2022-07-16 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('motivator', '0006_rename_mollie_id_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='amount_eur',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='refund',
            name='amount_eur',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
